{
  "swagger": "2.0",
  "info": {
    "description": "Factory Operations API",
    "version": "1.0.0",
    "title": "Factory Operations API"
  },
  "paths": {
    "/customer": {
      "post": {
        "summary": "Create a new customer",
        "parameters": [
          {
            "name": "customer",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Customer"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Customer created successfully",
            "schema": { "$ref": "#/definitions/Message" },
            "examples": { "application/json": { "message": "Created successfully!" }}
          },
          "400": {
            "description": "Invalid input or missing data",
            "schema": { "$ref": "#/definitions/ErrorResponse" },
            "examples": { "application/json": { "error": "Invalid", "details": "'customer_name' field is required." }}
          }
        }
      },
      "get": {
        "summary": "List all customers",
        "responses": {
          "200": {
            "description": "List of customers retrieved successfully",
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/Customer" }
            }
          }
        }
      }
    },
    "/customerAccount": {
      "post": {
        "summary": "Create a new customer account",
        "parameters": [
          {
            "name": "customerAccount",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CustomerAccount"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Customer account created successfully",
            "schema": { "$ref": "#/definitions/Message" }
          },
          "400": {
            "description": "Invalid input or missing data",
            "schema": { "$ref": "#/definitions/ErrorResponse" }
          }
        }
      },
      "get": {
        "summary": "List all customer accounts",
        "responses": {
          "200": {
            "description": "List of customer accounts retrieved successfully",
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/CustomerAccount" }
            }
          }
        }
      }
    },
    "/order": {
      "post": {
        "summary": "Create a new order",
        "parameters": [
          {
            "name": "order",
            "in": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Order" }
          }
        ],
        "responses": {
          "201": {
            "description": "Order created successfully",
            "schema": { "$ref": "#/definitions/Message" }
          },
          "400": {
            "description": "Invalid input or missing data",
            "schema": { "$ref": "#/definitions/ErrorResponse" }
          }
        }
      },
      "get": {
        "summary": "List all orders",
        "responses": {
          "200": {
            "description": "List of orders retrieved successfully",
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/Order" }
            }
          }
        }
      }
    },
    "/product": {
      "post": {
        "summary": "Create a new product",
        "parameters": [
          {
            "name": "product",
            "in": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Product" }
          }
        ],
        "responses": {
          "201": {
            "description": "Product created successfully",
            "schema": { "$ref": "#/definitions/Message" }
          },
          "400": {
            "description": "Invalid input or missing data",
            "schema": { "$ref": "#/definitions/ErrorResponse" }
          }
        }
      },
      "": {
        "summary": "Create a new product",
        "parameters": [
          {
            "name": "product",
            "in": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Product" }
          }
        ],
        "responses": {
          "201": {
            "description": "Product created successfully",
            "schema": { "$ref": "#/definitions/Message" }
          },
          "400": {
            "description": "Invalid input or missing data",
            "schema": { "$ref": "#/definitions/ErrorResponse" }
          }
        }
      },
      "get": {
        "summary": "List all products",
        "responses": {
          "200": {
            "description": "List of products retrieved successfully",
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/Product" }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Customer": {
      "type": "object",
      "properties": {
        "customer_id": { "type": "integer" },
        "customer_name": { "type": "string" },
        "customer_email": { "type": "string", "format": "email" },
        "customer_phone": { "type": "string" }
      },
      "required": ["customer_name", "customer_email", "customer_phone"]
    },
    "CustomerAccount": {
      "type": "object",
      "properties": {
        "account_id": { "type": "integer" },
        "customer_id": { "type": "integer" },
        "account_balance": { "type": "number", "format": "float" },
        "account_status": { "type": "string" }
      },
      "required": ["customer_id", "account_balance", "account_status"]
    },
    "Order": {
      "type": "object",
      "properties": {
        "order_id": { "type": "integer" },
        "customer_id": { "type": "integer" },
        "product_id": { "type": "integer" },
        "quantity": { "type": "integer" },
        "total_price": { "type": "number", "format": "float" }
      },
      "required": ["customer_id", "product_id", "quantity", "total_price"]
    },
    "Product": {
      "type": "object",
      "properties": {
        "product_id": { "type": "integer" },
        "product_name": { "type": "string" },
        "product_price": { "type": "number", "format": "float" }
      },
      "required": ["product_name", "product_price"]
    },
    "Message": {
      "type": "object",
      "properties": {
        "message": { "type": "string" }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "error": { "type": "string" },
        "details": { "type": "string" }
      }
    }
  }
}
